apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  backup:
    enabled: false
    image: perconalab/percona-server-mongodb-operator:main-backup
    runtimeClassName: container-rc
  crVersion: 1.15.0
  image: perconalab/percona-server-mongodb-operator:main-mongod5.0
  imagePullPolicy: Always
  multiCluster:
    enabled: true
  replsets:
  - affinity:
      antiAffinityTopologyKey: none
    configuration: |
      net:
        port: 27017
      operationProfiling:
        mode: slowOp
        slowOpThresholdMs: 100
      security:
        enableEncryption: true
        redactClientLogData: false
      setParameter:
        ttlMonitorSleepSecs: 60
        wiredTigerConcurrentReadTransactions: 128
        wiredTigerConcurrentWriteTransactions: 128
      storage:
        engine: wiredTiger
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
    expose:
      enabled: true
      exposeType: ClusterIP
    name: rs0
    resources:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 100m
        memory: 0.1G
    runtimeClassName: container-rc
    sidecars:
    - args:
      - -c
      - while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5;done
      command:
      - /bin/sh
      image: busybox
      name: rs-sidecar-1
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
  secrets:
    users: some-users
  sharding:
    configsvrReplSet:
      expose:
        enabled: true
        exposeType: ClusterIP
      runtimeClassName: container-rc
      sidecars:
      - args:
        - -c
        - while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5;done
        command:
        - /bin/sh
        image: busybox
        name: cfg-sidecar-1
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      configuration: |
        replication:
          localPingThresholdMs: 15
      expose:
        exposeType: ClusterIP
      runtimeClassName: container-rc
      sidecars:
      - args:
        - -c
        - while true; do echo echo $(date -u) 'test' >> /dev/null; sleep 5;done
        command:
        - /bin/sh
        image: busybox
        name: mongos-sidecar-1
      size: 3
  upgradeOptions:
    apply: Never
